
site_name: Machine Learning


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math


theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni


nav:
- Home: index.md


- Machine Learning:
  - Linear Regression: ml/LinearModels/Linear-models.md
  - Logistic Regression: ml/Classifiers/Logistic/Logistic.md
  - Decision Tree: ml/Classifiers/Tree/Tree.md
  - Ensamble Methods: ml/Classifiers/Ensamble/ensamble.md
  - Support Vector Machine: ml/Classifiers/SVM/svm.md
  - Kmeans Clustering: ml/Clustering/Kmeans/Kmeans.md
  - Agglomerative Clustering: ml/Clustering/Agglomerative/Agglomerative.md
  - Affinity Propagation: ml/Clustering/AffinityPropagation/Affinity-Propagation.md
  - Spectral Clustering: ml/Clustering/Spectral/Spectral.md
  - DBSCAN Clustering: ml/Clustering/DBSCAN/DBSCAN.md
  - Mean Shift Clustering: ml/Clustering/MeanShift/Mean-shift.md
  - Cluster Comparison: ml/Clustering/Comparison/Comparison.md


- ML Projects:
  - Introduction: mlp/intro.md
  - Boston Housing: mlp/boston_housing/boston_housing.md
  - Customer Clustering : mlp/Customer_segments/customer_segments.md
  - Finding Donors: mlp/finding_donors/finding_donors.md
  - Vehicle Detection: mlp/vehicle-detection/CARND-Project-5.md
  - Perceptron : mlp/perceptron/dlnd-your-first-neural-network.md


- Deep Learning:
  - Introduction: dl/intro.md
  - Vanila LSTM: dl/Vanila/1.Vanila-LSTM.md
  - Stacked LSTM: dl/stacked/2.Stacked-LSTM.md
  - Bidirectional LSTM: dl/bidirectional/5. BiDirectional-LSTM.md
  - Recurrent Neural Network: dl/rnn/RNN_project.md
  
- DL Projects:
    - Digit Classifier : dl/NMIST/NMIST.md
    - Image Classifier : dl/CIFRT10/CIFR10.md
    - Traffic Sign Detection : dl/traffic-sign/Traffic_Sign_Classifier.md
    - Language Translator: dl/translator/dlnd_language_translation.md
    
- Rinforcement Learning:
  - SmartCab : rl/smartcab/smartcab.md

- GAN Project:
  - Face Generation: dl/gan/dlnd_face_generation.md
  
- References: References/ref.md
 
